#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 testNumber jvmName
  exit
 fi
java -cp 'jars/*' -Djava.security.manager -Djava.security.policy=assembly.policy fr.upmc.components.extensions.examples.countDownLatch.DistributedAssembly $1 config.xml